name: kepler
description: Discover exoplanets with NASA data

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  sqflite: any
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  get: ^3.4.2
  http: any
  get_storage: ^1.2.1
  country_pickers: ^1.3.0
  csv: ^4.0.3
  dio: ^3.0.10
  json_async: ^0.1.1
  syncfusion_flutter_charts: ^18.2.56
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.3
  flare_flutter: ^2.0.6
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^0.1.9

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/main.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "#000000"
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.1

flutter:
  uses-material-design: true
  assets:
    - lib/locale/
    - lib/database/data.json
    - assets/images/
    - assets/flare/
  fonts:
   - family: JosefinSans
     fonts:
       - asset: fonts/JosefinSans.ttf
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Regular.ttf
   - family: Cabin
     fonts:
       - asset: fonts/Cabin.ttf