name: kepler
description: Discover exoplanets with NASA data

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  hive: ^1.4.4
  hive_flutter: ^0.3.1
  get: ^3.4.2
  http: any
  get_storage: ^1.2.1
  csv: ^4.0.3
  sqflite: any
  url_launcher: any
  json_async: ^0.1.1
  syncfusion_flutter_charts: ^18.2.59
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.3
  flare_flutter: ^2.0.6
  flutter_native_splash: ^0.1.9
  k_means_cluster: ^0.2.2

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/main.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.1

flutter:

  uses-material-design: true

  assets:
    - lib/locale/
    - assets/images/
    - assets/flare/shine.flr
    - assets/flare/clouds.flr
    - assets/flare/land.flr
    - assets/flare/pops.flr
    - assets/flare/holes.flr
    - assets/flare/gas.flr


  #   - images/a_dot_ham.jpeg

  fonts:
   - family: JosefinSans
     fonts:
       - asset: fonts/JosefinSans.ttf
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Regular.ttf
   - family: Cabin
     fonts:
       - asset: fonts/Cabin.ttf
