name: kepler
description: Discover exoplanets with NASA data

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  hive: ^1.4.4
  hive_flutter: ^0.3.1
  get: ^3.4.2
  http: any
  get_storage: ^1.2.1
  csv: ^4.0.3
  sqflite: any
  json_async: ^0.1.1
  syncfusion_flutter_charts: ^18.2.56
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.3
  flare_flutter: ^2.0.6
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^0.1.9

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/main.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "#000000"
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/locale/
    - assets/images/explorebg.png
    - assets/images/chartsbg.png
    - assets/images/favouritesbg.jpg
    - assets/flare/shine.flr
    - assets/flare/clouds.flr
    - assets/flare/land.flr
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
   - family: JosefinSans
     fonts:
       - asset: fonts/JosefinSans.ttf
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Regular.ttf
   - family: Cabin
     fonts:
       - asset: fonts/Cabin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
